"""empty message

Revision ID: f8baf73ebe4e
Revises: 20260211_initial
Create Date: 2026-02-15 22:50:36.309599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8baf73ebe4e'
down_revision: Union[str, Sequence[str], None] = '20260211_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('depression_tests', sa.Column('sleepy_tired', sa.String(), nullable=True))
    op.drop_index('ix_depression_tests_user_id', table_name='depression_tests')
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_mood_journaling_mood_id'), 'mood_journaling', ['mood_id'], unique=False)
    op.drop_column('users', 'daily_reminder_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_reminder_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_mood_journaling_mood_id'), table_name='mood_journaling')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.create_index('ix_depression_tests_user_id', 'depression_tests', ['user_id'], unique=False)
    op.drop_column('depression_tests', 'sleepy_tired')
    # ### end Alembic commands ###
